<!----------------------------------------------- Piè di Pagina ------------------------------------------------------>
<footer>

    <!----------------------------------------- Contenuto Footer ----------------------------------------------------->
    <div class="footerContent">

        <!-- Citazione -->
        <div class="footerCitation">
            <img alt="Logo" src="/images/logoHeader.png" class="logoFooter"/>

            <span class="textCitation">
                "La nuova era appartiene ai Code Crusaders: Creatori di possibilit&agrave; infinite"
            </span>
        </div>

        <!-- Menu di navigazione inferiore  -->
        <div class="footerMenu">

            <div class="containerColumn">
                <!-- Testo con forte importanza. Il contenuto al suo interno è solitamente visualizzato in grassetto-->
                <strong>Link</strong>
                <div class="verticalMenu">
                    <!-- Hyperlink -->
                    <a href="https://www.codecrusaders.com/home">
                        <span class="textFooter">Home</span>
                    </a>

                    <a href="https://www.codecrusaders.com/messaggi" >
                        <span class="textFooter">Messaggi</span>
                    </a>

                    <a href="https://www.codecrusaders.com/amici">
                        <span class="textFooter">Amici</span>
                    </a>

                    <a href="https://www.codecrusaders.com/eventi" >
                        <span class="textFooter">Eventi</span>
                    </a>

                    <a href="https://www.codecrusaders.com/account">
                        <span class="textFooter">Account</span>
                    </a>
                </div>
            </div>

            <div class="containerColumn">
                <strong>Assistenza Clienti</strong>
                <div class="verticalMenu">
                    <a href="https://www.codecrusaders.com/faq">
                        <span class="textFooter">FAQ - Domande Frequenti</span>
                    </a>

                    <a href="supporto">
                        <span class="textFooter">Supporto</span>
                    </a>
                </div>
            </div>

            <div class="containerColumn">
                <strong>Termini Legali</strong>
                <div class="verticalMenu">
                    <a href="https://www.codecrusaders.com/termini&condizioni">
                        <span class="textFooter">Termini &amp; Condizioni</span>
                    </a>

                    <a href="https://www.codecrusaders.com/informativa-privacy">
                        <span class="textFooter">Informativa sulla Privacy</span>
                    </a>

                    <a href="https://www.codecrusaders.com/cookie">
                        <span class="textFooter">Cookie</span>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <!-- Crediti -->
    <div class="footerCredits">
        <div class="divider"></div>
        <span class="footerContentCredits">
            Copyright &copy 2024 Code Crusaders Italia. Tutti i diritti riservati.
        </span>
    </div>

</footer>