<footer>
    <div class="thq-section-max-width">
        <div class="footer-content">

            <div class="footer-container">
                <img alt="Logo" src="/images/logoHeader.png" class="logoFooter"/>
                <span class="textMotto">
                    "La nuova era appartiene ai Code Crusaders: Creatori di possibilit&agrave; infinite"
                </span>
            </div>

        </div>

        <div class="footerCredits">
            <div class="divider"></div>
            <div>
                <span class="footerContentCredits">
                    Copyright &copy 2024 Code Crusaders Italia. Tutti i diritti riservati.
                </span>
            </div>
        </div>

    </div>
</footer>