<meta charset="utf-8" />

<title>CC: <%=menuActiveLink%></title>

<!-- Carattere di Google -->
<link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Inter:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap"
    data-tag="font"/>

<!-- External Style Information-->
<link rel="stylesheet" href="css/style.css" type="text/css">

<link rel="icon" href="/images/favicon.ico" type="image/x-icon">
