<header class="paddingNavbar">

    <img alt="Logo" src="/images/logoHeader.png" class="logoNavbar" />

    <!---------------------------------------- MENU desktop ---------------------------------------------------------->

    <!--sezione di navigazione -->
    <nav class="linkNavbar">
        <a href="https://www.codecrusaders.com/helpdesk/notifiche">
            <span class="textNavbar">Notifiche</span>
        </a>

        <a href="https://www.codecrusaders.com/helpdesk/account">
            <span class="textNavbar">Account</span>
        </a>

    </nav>

    <!-------------------------- MENU con logo e icona hamburger (mobile) ----------------------------------------->
    <div class="navbar-burger-menu">

        <!-- SVG scaricato da Google fonts -->
        <svg xmlns="http://www.w3.org/2000/svg"
             height="48px"
             viewBox="0 -960 960 960"
             width="48px"
             fill="#EFEFEF">

            <path d="M120-240v-60h720v60H120Zm0-210v-60h720v60H120Zm0-210v-60h720v60H120Z"/>
        </svg>
    </div>

    <!------------------------- MENU con link e icona x di chiusura (mobile) ------------------------------------->
    <div class="navbar-mobile-menu">

        <div class="navbar-nav">

            <div class="navbar-top">
                <img alt="logo" src="/images/logoHeader.png" class="navbar-logo"/>

                <div class="navbar-close-menu">
                    <!-- SVG scaricato da Google fonts -->
                    <svg xmlns="http://www.w3.org/2000/svg"
                         height="24px"
                         viewBox="0 -960 960 960"
                         width="24px"
                         fill="#EFEFEF">

                        <path d="m256-200-56-56 224-224-224-224 56-56 224 224 224-224 56 56-224 224 224 224-56 56-224-224-224 224Z"/>
                    </svg>
                </div>
            </div>

            <!------------------------- MENU con link e icona x di chiusura (mobile) --------------------------------->
            <nav class="navbar-links-mobile">
                <a href="https://www.codecrusaders.com/notifiche">
                    <span class="textNavbar">Notifiche</span>
                </a>

                <a href="https://www.codecrusaders.com/account">
                    <span class="textNavbar">Account</span>
                </a>

            </nav>

        </div>
    </div>
</header>